name: Password Checker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install bandit pip-audit pytest

    - name: Run Bandit (SAST)
      run: bandit -r password_checker.py

    - name: Run pip-audit (Dependency Scan)
      run: pip-audit

    - name: Run tests
      run: pytest || echo "No tests yet"
